// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_classify from "./routes/api/classify.ts";
import * as $api_intents from "./routes/api/intents.ts";
import * as $index from "./routes/index.tsx";
import * as $ChatInterface from "./islands/ChatInterface.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/classify.ts": $api_classify,
    "./routes/api/intents.ts": $api_intents,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChatInterface.tsx": $ChatInterface,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
